services:
  - type: web
    name: track-eta
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://track-eta-topaz.vercel.app
      - key: ALLOWED_ORIGINS
        sync: false
