const $ = id => document.getElementById(id);
let trains = [], currentTrain = '', currentData = null, socket = null, selectionId = 0, currentPage = 'home', speedAnimationFrame = 0;
const icons = {'Route delay':'📊','Dwell time overrun':'🚉','Signal congestion':'🚦','Weather conditions':'🌧️','Track conditions':'🔧'};
const titles = {home:'Track ETA',dashboard:'Live Train Dashboard',search:'Train Search',eta:'AI ETA Prediction',delay:'Delay Analytics',crowd:'Passenger Crowd Prediction',maintenance:'Maintenance Prediction',reports:'Reports'};
function showError(msg){$('error').style.display='block';$('error').textContent='⚠ '+msg;} function clearError(){$('error').style.display='none';}
function badge(status){return status==='arrived'?['✅ Arrived','on_time']:status==='stopped'?['⏸ Station stop','on_time']:status==='on_time'?['🟢 On Time','on_time']:status==='delayed'?['🟡 Delayed','delayed']:['🔴 Critical Delay','critical'];}
function topFactor(f){const a=Object.entries(f).sort((x,y)=>y[1]-x[1]);return a.length?a[0][0]:'Unknown';}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function animateSpeed(value, journeyComplete){
  const target=Number(value)||0;
  cancelAnimationFrame(speedAnimationFrame);
  const display=journeyComplete?'0 km/h':target.toFixed(1)+' km/h';
  $('curSpeed').textContent=display;
  $('liveSpeed').textContent=display;
  $('exSpeed').textContent=display;
}

function render(data, refreshDetails=false){
  if(!data || data.train_no !== currentTrain)return;
  const previousUpdatedAt=currentData&&currentData.updated_at;
  clearError(); currentData=data; $('connection').textContent='● Live server connected';
  $('routeSub').textContent=`Train ${data.train_no} · ${data.train_name}`; $('routeTitle').textContent=`${data.from_station} → ${data.to_station}`; $('etaValue').textContent=data.journey_complete?'Arrived':data.predicted_eta;
  const b=badge(data.journey_complete?'arrived':data.status); $('statusBadge').textContent=b[0]; $('statusBadge').className='badge '+b[1];
  $('curLoc').textContent=data.current_location; $('nextStation').textContent=data.next_station; $('curSpeed').textContent=data.current_speed_kmph+' km/h';
  $('fromLbl').textContent=data.from_station; $('toLbl').textContent=data.to_station; $('progressBar').style.width=data.progress_percent+'%'; $('schedEta').textContent=data.scheduled_eta; $('distCovered').textContent=data.distance_covered_km; $('distTotal').textContent=data.total_distance_km;
  $('factorsList').innerHTML=Object.entries(data.factors).map(([k,v])=>`<div class="factor"><span>${icons[k]||'•'} ${esc(k)}</span><b>+${v} min</b></div>`).join('');
  const primaryDelayReason=topFactor(data.factors); const referenceSpeed=Number(data.reference_speed_kmph)||0; const speedPercent=data.journey_complete||data.current_speed_kmph<=0?0:Math.min(100,(Number(data.current_speed_kmph)/Math.max(referenceSpeed,1))*100); $('whyLine').textContent=data.journey_complete?'Train has arrived at its destination. ETA prediction stopped.':data.is_stopped?`Train is stopped at ${data.current_location} for exactly ${data.station_stop_duration_minutes} minute. ${data.station_stop_remaining_seconds} seconds remaining.`:`Delay mainly driven by: ${primaryDelayReason}. Total predicted delay: +${data.delay_minutes} min.`; animateSpeed(data.current_speed_kmph,data.journey_complete); $('speedMeterFill').style.transition=data.journey_complete?'none':''; $('speedMeterFill').style.width=speedPercent+'%'; $('liveSpeedReference').textContent=`Timetable reference: ${referenceSpeed.toFixed(1)} km/h`; $('liveDelayValue').textContent='+'+Number(data.delay_minutes).toFixed(1)+' min'; $('liveUpdated').textContent=`Updated ${new Date(data.updated_at).toLocaleTimeString('en-IN',{hour12:false})}`; $('liveSource').textContent=`Data source: ${data.source==='live-provider'?'Authorized live provider':data.source==='simulation-fallback'?'Simulation fallback':'Demo simulation'}`; $('avgTravelTime').textContent=data.average_travel_time||'—';
  $('etaModuleValue').textContent=data.predicted_eta; $('confidenceScore').textContent=Math.max(82,Math.round(97-data.delay_minutes/2))+'%'; $('delayProbability').textContent=Math.min(99,Math.round(data.delay_minutes*3.2+18))+'%';
  $('exSpeed').textContent=data.current_speed_kmph+' km/h'; $('exDistance').textContent=Math.max(0,Math.round(data.total_distance_km-data.distance_covered_km))+' km'; $('exWeather').textContent=data.weather; $('exCrossing').textContent=data.factors['Signal congestion']>6?'Possible crossing hold':'Clear';
  const factors=Object.entries(data.factors||{}).filter(([,value])=>Number.isFinite(Number(value))); $('delayFactors').innerHTML=factors.map(([k,v])=>`<div class="factor"><span>${esc(k)}</span><b>${Number(v).toFixed(1)} min</b></div>`).join('')||'<div class="empty">No delay factors available.</div>'; $('delayTotal').textContent='+'+Number(data.delay_minutes).toFixed(1)+' min'; $('delayTop').textContent=topFactor(Object.fromEntries(factors)); $('delayStatus').textContent=b[0];
  updateMap(data); if(!data.journey_complete)drawChart(data.eta_history||[]);
  if(refreshDetails||data.updated_at!==previousUpdatedAt){loadCrowd(data.train_no, selectionId); loadMaintenance();}
}
async function loadTrains(){try{trains=await getJSON('/api/trains'); $('trainCount').textContent=trains.length; $('heroTrainCount').textContent=trains.length; $('trainSelect').innerHTML=trains.map(t=>`<option value="${t.train_no}">${t.train_no} — ${t.name}</option>`).join(''); currentTrain=trains[0].train_no; renderHomeList(); connectSocket(); await refreshLive(); await refreshStats(); renderSearch(); loadCrowdOverview();}catch(e){$('connection').textContent='● Server connection failed';showError('Cannot connect to Node.js backend. Run npm start. '+e.message);}}
function connectSocket(){if(socket)socket.disconnect();socket=io(API_BASE_URL,{transports:["websocket","polling"]});socket.on('connect',()=>{ $('connection').textContent='● Real-time socket connected'; socket.emit('subscribe',currentTrain);});socket.on('train:update',data=>{if(data.train_no===currentTrain)render(data);});socket.on('connect_error',()=>{$('connection').textContent='● Socket connection failed';});}
async function refreshLive(trainNo=currentTrain, requestId=selectionId){const data=await getJSON(`/api/train/${trainNo}/live`);if(trainNo===currentTrain&&requestId===selectionId)render(data,true);}
async function refreshStats(){const s=await getJSON('/api/stats');$('homeOnTime').textContent=s.on_time;$('homeDelayed').textContent=s.delayed;$('homeCritical').textContent=s.critical;$('homeCrowd').textContent=s.high_crowd;}
function renderHomeList(){ $('homeTrainList').innerHTML=trains.map(t=>`<button class="train-item" data-train="${t.train_no}"><span><b>${t.train_no}</b> ${esc(t.name)}</span><small>${esc(t.from)} → ${esc(t.to)}</small></button>`).join('');document.querySelectorAll('.train-item').forEach(b=>b.onclick=()=>selectTrain(b.dataset.train,'dashboard')); }
function showLiveDashboard(){showPage('dashboard');}
function selectTrain(no,targetPage=currentPage){selectionId+=1;const requestId=selectionId;currentTrain=no;currentData=null;$('trainSelect').value=no;$('delayFactors').innerHTML='<div class="empty">Loading delay factors...</div>';$('delayTotal').textContent='—';$('delayTop').textContent='—';$('delayStatus').textContent='Loading';connectSocket();refreshLive(no,requestId).catch(e=>{if(requestId===selectionId)showError(e.message);});if(targetPage==='home')showLiveDashboard();else showPage(targetPage);}
async function resetCurrentTrain(){const button=$('resetTrain');const requestId=++selectionId;button.disabled=true;button.textContent='↺ Resetting...';try{const response=await fetch(apiUrl(`/api/train/${currentTrain}/reset`),{method:'POST'});if(!response.ok)throw new Error(`Server returned ${response.status}`);const result=await response.json();resetMap();connectSocket();if(requestId===selectionId)render(result.snapshot,true);clearError();}catch(e){showError(`Unable to reset train: ${e.message}`);}finally{button.disabled=false;button.textContent='↺ Reset Train';}}
function renderSearch(filter=''){const q=filter.toLowerCase();const list=trains.filter(t=>[t.train_no,t.name,t.from,t.to,t.category].join(' ').toLowerCase().includes(q));$('searchResults').innerHTML=list.map(t=>`<article class="search-card train-detail-card"><div class="train-detail-main"><div class="train-detail-heading"><b>${t.train_no} · ${esc(t.name)}</b><span class="train-category">${esc(t.category||'Train Service')}</span></div><p>${esc(t.from)} <span class="route-arrow">→</span> ${esc(t.to)}</p><small class="train-distance">${t.distance_km} km route · Average travel: ${esc(t.average_travel_time||'—')} · ${t.category==='Short Distance'?'Short-distance service':'Long-distance service'}</small></div><button class="secondary" data-train="${t.train_no}">Track</button></article>`).join('')||'<div class="empty">No trains found.</div>';document.querySelectorAll('#searchResults [data-train]').forEach(b=>b.onclick=()=>selectTrain(b.dataset.train,'home'));}
async function loadCrowd(trainNo=currentTrain, requestId=selectionId){try{const d=await getJSON(`/api/crowd/${trainNo}`);if(trainNo!==currentTrain||requestId!==selectionId)return;const crowdClass=d.level.toLowerCase().replace(' ','-');const crowdColor=d.level==='High Crowd'?'var(--red)':d.level==='Medium'?'var(--yellow)':'var(--green)';$('crowdTrainName').textContent=`${d.train_no} · ${d.train_name}`;$('crowdRoute').textContent=d.route;$('crowdCurrentLocation').textContent=d.current_location;$('crowdStation').textContent=d.station;$('crowdFestival').textContent=d.inputs.festival_calendar?'Yes':'No';$('crowdBookings').textContent=d.inputs.ticket_bookings;$('crowdPrevious').textContent=d.inputs.previous_passenger_count;$('crowdMeter').style.setProperty('--crowd-score',`${d.score}%`);$('crowdMeter').style.width='0%';requestAnimationFrame(()=>{$('crowdMeter').style.width=d.score+'%';});$('crowdLevel').textContent=d.level;$('crowdLevel').className='crowd-level '+crowdClass;$('crowdLevel').style.color=crowdColor;$('crowdScore').textContent=d.score+' / 100';$('crowdUpdated').textContent=`Updated ${new Date(d.updated_at).toLocaleTimeString('en-IN',{hour12:false})}`;}catch(e){if(trainNo===currentTrain&&requestId===selectionId)showError(`Passenger details unavailable: ${e.message}`);}}
async function loadCrowdOverview(){try{const forecasts=await Promise.all(trains.map(async train=>({train,...await getJSON(`/api/crowd/${train.train_no}`)})));$('crowdTrainList').innerHTML=forecasts.map(({train,score,level,station,inputs},index)=>{const color=level==='High Crowd'?'var(--red)':level==='Medium'?'var(--yellow)':'var(--green)';return `<article class="crowd-train train-detail-card" style="--row-index:${index}"><div class="train-detail-main"><div class="train-detail-heading"><b>${train.train_no} · ${esc(train.name)}</b><span class="train-category">${esc(train.category||'Train Service')}</span></div><p>Next station: ${esc(station)}</p><small class="train-distance">${train.distance_km} km route · ${inputs.festival_calendar?'Festival demand active':'Regular demand'}</small><small class="crowd-inputs">Bookings: ${inputs.ticket_bookings} · Previous passengers: ${inputs.previous_passenger_count}</small></div><div class="crowd-result"><strong style="color:${color}">${level}</strong><small>${score} / 100</small><button class="secondary" data-train="${train.train_no}">Track</button></div></article>`;}).join('');document.querySelectorAll('#crowdTrainList [data-train]').forEach(button=>button.onclick=()=>selectTrain(button.dataset.train));}catch(e){$('crowdTrainList').innerHTML='<div class="empty">Crowd forecasts unavailable.</div>';}}
function setupCrowdMotion(){if(document.getElementById('crowdMotionStyles'))return;const style=document.createElement('style');style.id='crowdMotionStyles';style.textContent='.crowd-overview{margin-top:18px}.crowd-train-list{display:grid;gap:8px}.crowd-train{opacity:0;transform:translateY(8px);animation:crowdRowIn .45s ease forwards;animation-delay:calc(var(--row-index,0) * 55ms)}.crowd-train:hover{transform:translateY(-2px)}.crowd-card{position:relative;overflow:hidden}.crowd-card:after{content:"";position:absolute;inset:-40%;background:conic-gradient(from 0deg,transparent,var(--blue),transparent 22%);opacity:.08;animation:crowdOrbit 5s linear infinite;pointer-events:none}.crowd-meter{position:relative;z-index:1;height:12px;margin:18px 0 12px;border-radius:999px;background:#091524;overflow:hidden;border:1px solid var(--line)}.crowd-meter i{display:block;height:100%;width:0;border-radius:inherit;background:linear-gradient(90deg,var(--green),var(--yellow),var(--red));box-shadow:0 0 18px rgba(66,169,255,.45);transition:width 1.1s cubic-bezier(.22,.8,.3,1)}.crowd-level{display:inline-block;margin-top:8px;animation:crowdPulse 2.4s ease-in-out infinite}.level-list{display:flex;flex-direction:column;gap:10px}.level-list strong{font-size:24px;color:var(--blue)}@keyframes crowdRowIn{to{opacity:1;transform:translateY(0)}}@keyframes crowdPulse{0%,100%{filter:brightness(1);transform:scale(1)}50%{filter:brightness(1.25);transform:scale(1.04)}}@keyframes crowdOrbit{to{transform:rotate(360deg)}}@media(prefers-reduced-motion:reduce){.crowd-train,.crowd-level,.crowd-card:after{animation:none}.crowd-train{opacity:1;transform:none}.crowd-meter i{transition:none}}';document.head.appendChild(style);}
function setupTrainDetailCards(){if(document.getElementById('trainDetailStyles'))return;const style=document.createElement('style');style.id='trainDetailStyles';style.textContent='.train-detail-card{min-height:154px;padding:28px 30px!important}.train-detail-main{min-width:0}.train-detail-heading{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.train-detail-heading b{font-size:18px}.train-category{border:1px solid var(--line);border-radius:999px;padding:4px 9px;color:var(--blue);font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.train-detail-card p{margin:12px 0 5px;color:#a9c5eb;font-size:15px}.route-arrow{color:var(--blue);padding:0 4px}.train-distance{color:var(--muted);font-size:11px}.train-detail-card .secondary{min-width:104px;min-height:58px;font-size:16px}.train-detail-card:hover{border-color:var(--blue);transform:translateY(-2px);box-shadow:0 10px 24px rgba(0,0,0,.18)}@media(max-width:600px){.train-detail-card{padding:20px!important;align-items:flex-start}.train-detail-card .secondary{min-width:88px;min-height:48px}}';document.head.appendChild(style);}
function setupCrowdDetailCards(){if(document.getElementById('crowdDetailStyles'))return;const style=document.createElement('style');style.id='crowdDetailStyles';style.textContent='.crowd-train{display:flex;align-items:center;justify-content:space-between;gap:18px;width:100%;text-align:left}.crowd-inputs{display:block;color:var(--muted);font-size:11px;margin-top:5px}.crowd-result{display:flex;align-items:flex-end;flex-direction:column;gap:6px;min-width:116px}.crowd-result strong{font-size:14px}.crowd-result small{color:var(--muted)}.crowd-result button{margin-top:5px}@media(max-width:600px){.crowd-train{align-items:flex-start}.crowd-result{min-width:90px}}';document.head.appendChild(style);}
async function loadMaintenance(){try{const d=await getJSON(`/api/maintenance/${currentTrain}`);$('healthScore').textContent=d.health_score;$('maintenanceList').innerHTML=[['Brake inspection',d.brake_inspection],['Wheel replacement',d.wheel_replacement],['Engine servicing',d.engine_servicing]].map(x=>`<div class="maint"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');$('maintenanceBasis').textContent=d.basis||'';}catch(e){}}
async function loadReports(){try{const list=await getJSON('/api/reports');$('reportBody').innerHTML=list.map(x=>`<tr><td><b>${x.train_no}</b> ${esc(x.train_name)}</td><td>${esc(x.route)}</td><td>+${x.delay} min</td><td>${x.crowd}/100</td><td><span class="table-status ${x.status}">${x.status}</span></td></tr>`).join('');}catch(e){showError(e.message);}}
function showPage(page){currentPage=page;document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$('page-'+page).classList.add('active');$('page-dashboard').classList.remove('home-dashboard');if(page==='home'){$('page-dashboard').classList.add('active','home-dashboard');}$('topActions').classList.toggle('search-page',page==='search');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===page));$('pageTitle').textContent=titles[page];if(page==='home'||page==='dashboard'){resizeMap();if(currentData)updateMap(currentData);}if(page==='reports')loadReports();if(page==='search')renderSearch($('searchInput').value);}

setupCrowdMotion();document.querySelectorAll('.nav').forEach(n=>n.addEventListener('click',()=>showPage(n.dataset.page)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>b.dataset.go==='dashboard'?showLiveDashboard():showPage(b.dataset.go)));
$('trainSelect').addEventListener('change',()=>selectTrain($('trainSelect').value));$('searchInput').addEventListener('input',e=>renderSearch(e.target.value));$('refreshReports').addEventListener('click',loadReports);
$('resetTrain').addEventListener('click',resetCurrentTrain);
setupTrainDetailCards();setupCrowdDetailCards();loadTrains();
showPage('home');
